import type {Metadata} from "next";
import "./globals.css";
import "@mantine/core/styles.css";
import {
    ColorSchemeScript,
    MantineProvider,
    mantineHtmlProps,
} from "@mantine/core";
import {theme} from "../theme";
import AppShellClient from "@frontend/components/layout/AppShellClient";
import {AuthProvider} from "@frontend/contexts/AuthContext";

export const metadata: Metadata = {
    title: "Chrono-tracker",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" {...mantineHtmlProps}>
            <head>
                <ColorSchemeScript/>
            </head>
            <body>
                <MantineProvider theme={theme}>
                    <AuthProvider>
                        <AppShellClient>{children}</AppShellClient>
                    </AuthProvider>
                </MantineProvider>
            </body>
        </html>
    );
}
