services:
  mysql:
    image: mysql:8.0
    env_file:
      - ./backend/.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/init:/docker-entrypoint-initdb.d
    networks:
      - chrono-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  shared:
    build:
      context: .
      dockerfile: ./shared.Dockerfile
      target: development
    volumes:
      - .:/workspace
      - /workspace/node_modules
    networks:
      - chrono-network
    working_dir: /workspace/shared
    healthcheck:
      test: [ "CMD", "test", "-f", "/workspace/shared/dist/index.js" ]
      interval: 15s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: ./backend/docker/Dockerfile
      target: development
    ports:
      - "3333:3333"
    volumes:
      - .:/workspace
      - /workspace/node_modules
      - /workspace/backend/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      shared:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      - chrono-network
    working_dir: /workspace/backend
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3333/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: ./frontend/docker/Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - .:/workspace
      - /workspace/node_modules
      - /workspace/frontend/node_modules
      - /workspace/frontend/.next
    depends_on:
      shared:
        condition: service_healthy
      backend:
        condition: service_started
    networks:
      - chrono-network
    working_dir: /workspace/frontend
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql_data:

networks:
  chrono-network:
    driver: bridge
