services:
  mysql:
    image: mysql:8.0
    env_file:
      - ./backend/.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/init:/docker-entrypoint-initdb.d
    networks:
      - chrono-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: ./backend/docker/Dockerfile
      target: development
    ports:
      - "3333:3333"
    volumes:
      - .:/workspace
      - /workspace/node_modules
      - /workspace/backend/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - chrono-network
    working_dir: /workspace/backend

  frontend:
    build:
      context: .
      dockerfile: ./frontend/docker/Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - .:/workspace
      - /workspace/node_modules
      - /workspace/frontend/node_modules
      - /workspace/frontend/.next
    depends_on:
      - backend
    networks:
      - chrono-network
    working_dir: /workspace/frontend

volumes:
  mysql_data:

networks:
  chrono-network:
    driver: bridge
