services:
  mysql:
    image: mysql:8.0
    env_file:
      - ./backend/.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/init:/docker-entrypoint-initdb.d
    networks:
      - chrono-network
    restart: unless-stopped

  shared:
    build:
      context: ./shared
      dockerfile: docker/Dockerfile
      target: development
    volumes:
      - ./shared:/app
      - /app/node_modules
      - shared_dist:/app/dist
    networks:
      - chrono-network

  backend:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
      target: development
    ports:
      - "3333:3333"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - shared_dist:/app/node_modules/@chrono-tracker/shared/dist
    env_file:
      - ./backend/.env
    depends_on:
      - shared
      - mysql
    networks:
      - chrono-network

  frontend:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
      - shared_dist:/app/node_modules/@chrono-tracker/shared/dist
    depends_on:
      - shared
      - backend
    networks:
      - chrono-network

volumes:
  shared_dist:
  mysql_data:

networks:
  chrono-network:
    driver: bridge
